test : compile
	./test

compile :
	g++ test.cpp -o test

clean :
	rm test

############################

exo1 : compile1
	./exo1

compile1 :
	g++ exo1.cpp -o exo1

clean1 :
	rm exo1

############################

exo2 : compile2
	./exo2

compile2 :
	g++ exo2.cpp -o exo2

clean2 :
	rm exo2

############################

exo3 : compile3
	./exo3

compile3 :
	g++ exo3.cpp -o exo3

clean3 :
	rm exo3

############################

cleanGlobal :
	rm test	 exo1 exo2 exo3
